#!/bin/bash
REPO_BASE=$HOME/repos
GUI="xorg slim awesome thunar terminator chromium"
CLI="irssi ranger tmux hsetroot"
DEV="vim-gtk git bzr python-pip"
PIP="virtualenv virtualenvwrapper pyflakes autopep8"

sudo apt-get install -y $GUI
sudo apt-get install -y $DEV
sudo apt-get install -y $CLI
sudo pip install $PIP

REPO_BASE=$HOME/repos

mkdir $REPO_BASE
git clone http://github.com/omaraboumrad/dot.git $REPO_BASE/dot

git config --global user.name "Omar Abou Mrad"
git config --global user.email omar.aboumrad@gmail.com
bzr whoami "Omar Abou Mrad <omar.aboumrad@rezayat.net>"

cd /usr/share/fonts/truetype/
 
# FONT
sudo mkdir ttf-monaco
cd ttf-monaco/
sudo wget http://www.gringod.com/wp-upload/software/Fonts/Monaco_Linux.ttf
sudo mkfontdir
cd ..
fc-cache

# GO BACK HOME AT THE END
cd $HOME
