#!/bin/bash
REPO_BASE=$HOME/repos
GUI="xorg slim awesome rxvt-unicode chromium"
CLI="irssi ranger tmux hsetroot bitlbee"
DEV="vim-gtk git bzr python-pip"
DRV="firmware-iwlwifi alsa-base pulseaudio"
PIP="virtualenv virtualenvwrapper pyflakes autopep8"

sudo apt-get install -y $GUI
sudo apt-get install -y $DEV
sudo apt-get install -y $CLI
sudo apt-get install -y $DRV
sudo pip install $PIP

REPO_BASE=$HOME/repos

mkdir $REPO_BASE
git clone http://github.com/omaraboumrad/dot.git $REPO_BASE/dot

git config --global user.name "Omar Abou Mrad"
git config --global user.email omar.aboumrad@gmail.com
bzr whoami "Omar Abou Mrad <omar.aboumrad@rezayat.net>"

