#!/bin/bash

cd ~/projects/vagrant/ctc
(VBoxManage list runningvms | grep ctc) || vagrant up
tmux -2 new-session -d -s CTC -n main
tmux split-window -h -p 50
tmux send-keys -t 0 vim C-m
tmux send-keys -t 1 python C-m
tmux new-window -n server
tmux send-keys -t 0 'vagrant ssh' C-m
sleep 2
tmux new-window -n shell 
tmux send-keys -t 0 'vagrant ssh' C-m
tmux new-window -n misc
tmux attach

